<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
  <testsuite id="0" name="C:\code\mail-service\src\controllers\SendMailController.test.ts" errors="0" package="C:\code\mail-service\src\controllers\SendMailController.test.ts" hostname="localhost" tests="9" failures="7" time="1.31" timestamp="2018-01-10T00:10:34">
    <properties>
    </properties>
    <testcase classname="sendMail method tests" name="will send a message with 2 working MailServices" time="0">
      <failure message="Error: Query.orderByPriority: You can&apos;t combine multiple orderBy calls.
    at Query.Object.&lt;anonymous&gt;.Query.validateNoPreviousOrderByCall_ (C:\code\mail-service\node_modules\@firebase\database\dist\cjs\src\src\api\Query.ts:168:13)
    at Query.Object.&lt;anonymous&gt;.Query.orderByPriority (C:\code\mail-service\node_modules\@firebase\database\dist\cjs\src\src\api\Query.ts:467:10)
    at SendMailController.listenForPendingEmails (C:\code\mail-service\src\controllers\SendMailController.ts:84:9)
    at new SendMailController (C:\code\mail-service\src\controllers\SendMailController.ts:25:14)
    at Object.test (C:\code\mail-service\src\controllers\SendMailController.test.ts:42:56)
    at Object.asyncFn (c:\code\mail-service\node_modules\jest-jasmine2\build\jasmine_async.js:124:345)
    at resolve (c:\code\mail-service\node_modules\jest-jasmine2\build\queue_runner.js:51:12)
    at new Promise (&lt;anonymous&gt;)
    at mapper (c:\code\mail-service\node_modules\jest-jasmine2\build\queue_runner.js:40:274)
    at promise.then (c:\code\mail-service\node_modules\jest-jasmine2\build\queue_runner.js:83:39)
    at &lt;anonymous&gt;
    at process._tickCallback (internal/process/next_tick.js:188:7)" type="AssertionError">
      </failure>
    </testcase>
    <testcase classname="sendMail method tests" name="will send a message with 100 working MailServices" time="0">
      <failure message="Error: Query.orderByPriority: You can&apos;t combine multiple orderBy calls.
    at Query.Object.&lt;anonymous&gt;.Query.validateNoPreviousOrderByCall_ (C:\code\mail-service\node_modules\@firebase\database\dist\cjs\src\src\api\Query.ts:168:13)
    at Query.Object.&lt;anonymous&gt;.Query.orderByPriority (C:\code\mail-service\node_modules\@firebase\database\dist\cjs\src\src\api\Query.ts:467:10)
    at SendMailController.listenForPendingEmails (C:\code\mail-service\src\controllers\SendMailController.ts:84:9)
    at new SendMailController (C:\code\mail-service\src\controllers\SendMailController.ts:25:14)
    at Object.test (C:\code\mail-service\src\controllers\SendMailController.test.ts:49:56)
    at Object.asyncFn (c:\code\mail-service\node_modules\jest-jasmine2\build\jasmine_async.js:124:345)
    at resolve (c:\code\mail-service\node_modules\jest-jasmine2\build\queue_runner.js:51:12)
    at new Promise (&lt;anonymous&gt;)
    at mapper (c:\code\mail-service\node_modules\jest-jasmine2\build\queue_runner.js:40:274)
    at promise.then (c:\code\mail-service\node_modules\jest-jasmine2\build\queue_runner.js:83:39)
    at &lt;anonymous&gt;
    at process._tickCallback (internal/process/next_tick.js:188:7)" type="AssertionError">
      </failure>
    </testcase>
    <testcase classname="sendMail method tests" name="will send a message when 3/4 services are down" time="0">
      <failure message="Error: Query.orderByPriority: You can&apos;t combine multiple orderBy calls.
    at Query.Object.&lt;anonymous&gt;.Query.validateNoPreviousOrderByCall_ (C:\code\mail-service\node_modules\@firebase\database\dist\cjs\src\src\api\Query.ts:168:13)
    at Query.Object.&lt;anonymous&gt;.Query.orderByPriority (C:\code\mail-service\node_modules\@firebase\database\dist\cjs\src\src\api\Query.ts:467:10)
    at SendMailController.listenForPendingEmails (C:\code\mail-service\src\controllers\SendMailController.ts:84:9)
    at new SendMailController (C:\code\mail-service\src\controllers\SendMailController.ts:25:14)
    at Object.test (C:\code\mail-service\src\controllers\SendMailController.test.ts:58:16)
    at Object.asyncFn (c:\code\mail-service\node_modules\jest-jasmine2\build\jasmine_async.js:124:345)
    at resolve (c:\code\mail-service\node_modules\jest-jasmine2\build\queue_runner.js:51:12)
    at new Promise (&lt;anonymous&gt;)
    at mapper (c:\code\mail-service\node_modules\jest-jasmine2\build\queue_runner.js:40:274)
    at promise.then (c:\code\mail-service\node_modules\jest-jasmine2\build\queue_runner.js:83:39)
    at &lt;anonymous&gt;
    at process._tickCallback (internal/process/next_tick.js:188:7)" type="AssertionError">
      </failure>
    </testcase>
    <testcase classname="sendMail method tests" name="will not send a message when 4/4 services are down" time="0">
      <failure message="Error: Query.orderByPriority: You can&apos;t combine multiple orderBy calls.
    at Query.Object.&lt;anonymous&gt;.Query.validateNoPreviousOrderByCall_ (C:\code\mail-service\node_modules\@firebase\database\dist\cjs\src\src\api\Query.ts:168:13)
    at Query.Object.&lt;anonymous&gt;.Query.orderByPriority (C:\code\mail-service\node_modules\@firebase\database\dist\cjs\src\src\api\Query.ts:467:10)
    at SendMailController.listenForPendingEmails (C:\code\mail-service\src\controllers\SendMailController.ts:84:9)
    at new SendMailController (C:\code\mail-service\src\controllers\SendMailController.ts:25:14)
    at Object.test (C:\code\mail-service\src\controllers\SendMailController.test.ts:64:56)
    at Object.asyncFn (c:\code\mail-service\node_modules\jest-jasmine2\build\jasmine_async.js:124:345)
    at resolve (c:\code\mail-service\node_modules\jest-jasmine2\build\queue_runner.js:51:12)
    at new Promise (&lt;anonymous&gt;)
    at mapper (c:\code\mail-service\node_modules\jest-jasmine2\build\queue_runner.js:40:274)
    at promise.then (c:\code\mail-service\node_modules\jest-jasmine2\build\queue_runner.js:83:39)
    at &lt;anonymous&gt;
    at process._tickCallback (internal/process/next_tick.js:188:7)" type="AssertionError">
      </failure>
    </testcase>
    <testcase classname="sendMail method tests" name="will still send a message if 9/10 services are down" time="0">
      <failure message="Error: Query.orderByPriority: You can&apos;t combine multiple orderBy calls.
    at Query.Object.&lt;anonymous&gt;.Query.validateNoPreviousOrderByCall_ (C:\code\mail-service\node_modules\@firebase\database\dist\cjs\src\src\api\Query.ts:168:13)
    at Query.Object.&lt;anonymous&gt;.Query.orderByPriority (C:\code\mail-service\node_modules\@firebase\database\dist\cjs\src\src\api\Query.ts:467:10)
    at SendMailController.listenForPendingEmails (C:\code\mail-service\src\controllers\SendMailController.ts:84:9)
    at new SendMailController (C:\code\mail-service\src\controllers\SendMailController.ts:25:14)
    at Object.test (C:\code\mail-service\src\controllers\SendMailController.test.ts:73:16)
    at Object.asyncFn (c:\code\mail-service\node_modules\jest-jasmine2\build\jasmine_async.js:124:345)
    at resolve (c:\code\mail-service\node_modules\jest-jasmine2\build\queue_runner.js:51:12)
    at new Promise (&lt;anonymous&gt;)
    at mapper (c:\code\mail-service\node_modules\jest-jasmine2\build\queue_runner.js:40:274)
    at promise.then (c:\code\mail-service\node_modules\jest-jasmine2\build\queue_runner.js:83:39)
    at &lt;anonymous&gt;
    at process._tickCallback (internal/process/next_tick.js:188:7)" type="AssertionError">
      </failure>
    </testcase>
    <testcase classname="sendMail method tests" name="will still send a message if 49/50 services are down" time="0">
      <failure message="Error: Query.orderByPriority: You can&apos;t combine multiple orderBy calls.
    at Query.Object.&lt;anonymous&gt;.Query.validateNoPreviousOrderByCall_ (C:\code\mail-service\node_modules\@firebase\database\dist\cjs\src\src\api\Query.ts:168:13)
    at Query.Object.&lt;anonymous&gt;.Query.orderByPriority (C:\code\mail-service\node_modules\@firebase\database\dist\cjs\src\src\api\Query.ts:467:10)
    at SendMailController.listenForPendingEmails (C:\code\mail-service\src\controllers\SendMailController.ts:84:9)
    at new SendMailController (C:\code\mail-service\src\controllers\SendMailController.ts:25:14)
    at Object.test (C:\code\mail-service\src\controllers\SendMailController.test.ts:81:16)
    at Object.asyncFn (c:\code\mail-service\node_modules\jest-jasmine2\build\jasmine_async.js:124:345)
    at resolve (c:\code\mail-service\node_modules\jest-jasmine2\build\queue_runner.js:51:12)
    at new Promise (&lt;anonymous&gt;)
    at mapper (c:\code\mail-service\node_modules\jest-jasmine2\build\queue_runner.js:40:274)
    at promise.then (c:\code\mail-service\node_modules\jest-jasmine2\build\queue_runner.js:83:39)
    at &lt;anonymous&gt;
    at process._tickCallback (internal/process/next_tick.js:188:7)" type="AssertionError">
      </failure>
    </testcase>
    <testcase classname="getMiddleware method tests" name="can get express middleware" time="0">
      <failure message="Error: Query.orderByPriority: You can&apos;t combine multiple orderBy calls.
    at Query.Object.&lt;anonymous&gt;.Query.validateNoPreviousOrderByCall_ (C:\code\mail-service\node_modules\@firebase\database\dist\cjs\src\src\api\Query.ts:168:13)
    at Query.Object.&lt;anonymous&gt;.Query.orderByPriority (C:\code\mail-service\node_modules\@firebase\database\dist\cjs\src\src\api\Query.ts:467:10)
    at SendMailController.listenForPendingEmails (C:\code\mail-service\src\controllers\SendMailController.ts:84:9)
    at new SendMailController (C:\code\mail-service\src\controllers\SendMailController.ts:25:14)
    at Function.bootstrap (C:\code\mail-service\src\controllers\SendMailController.ts:37:16)
    at Object.test (C:\code\mail-service\src\controllers\SendMailController.test.ts:107:75)
    at Object.asyncFn (c:\code\mail-service\node_modules\jest-jasmine2\build\jasmine_async.js:124:345)
    at resolve (c:\code\mail-service\node_modules\jest-jasmine2\build\queue_runner.js:51:12)
    at new Promise (&lt;anonymous&gt;)
    at mapper (c:\code\mail-service\node_modules\jest-jasmine2\build\queue_runner.js:40:274)
    at promise.then (c:\code\mail-service\node_modules\jest-jasmine2\build\queue_runner.js:83:39)
    at &lt;anonymous&gt;
    at process._tickCallback (internal/process/next_tick.js:188:7)" type="AssertionError">
      </failure>
    </testcase>
    <system-out/>
    <system-err/>
  </testsuite>
</testsuites>